<?php

namespace App\Support;

class SilvaProjectsDefaults
{
    public static function places(): array
    {
        return \App\Models\ProjectPlace::filterMap();
    }

    public static function types(): array
    {
        return \App\Models\ProjectType::filterMap();
    }

    public static function data(): array
    {
        return [
            'intro' => [
                'kicker' => 'Uygulamalar',
                'title' => 'Projeler',
                'aside' => 'Otel lobisinden villa cephesine. İç mekân, dış mekân ve şehirle süzün.',
            ],
            'filter' => [
                'place_label' => 'Mekân',
                'type_label' => 'Tip',
                'all_cities' => 'Tüm şehirler',
                'count_suffix' => 'proje',
                'reset' => 'Sıfırla',
                'empty_title' => 'Bu seçime uygun proje yok.',
                'empty_reset' => 'Filtrelemeyi sıfırla',
            ],
            'detail' => [
                'notes_kicker' => 'Uygulama',
                'notes_title' => 'Notlar',
                'related_kicker' => 'Keşfet',
                'related_title' => 'Diğer uygulamalar',
                'story_kicker' => 'Hikâye',
                'surface_kicker' => 'Yüzey',
                'surface_hint' => 'Kullanılan panel',
                'cta' => 'Bu uygulamayı konuş',
                'type_projects' => 'projeleri',
                'facts' => [
                    'city' => 'Şehir',
                    'place' => 'Mekân',
                    'type' => 'Tip',
                    'product' => 'Yüzey',
                    'year' => 'Yıl',
                    'area' => 'Alan',
                ],
            ],
        ];
    }

    public static function seedItems(): array
    {
        return [
            [
                'slug' => 'lobi-feature-wall',
                'title' => 'Lobi feature wall',
                'type' => 'otel',
                'place' => 'indoor',
                'city' => 'istanbul',
                'city_label' => 'İstanbul',
                'product_name' => 'Slate Antrasit',
                'year' => '2025',
                'area' => '86 m²',
                'main_image' => 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1400&q=85',
                    'silvastone/assets/hero/slate-antrasit.jpg',
                ],
                'lead' => 'İstanbul’da bir butik otel lobisinde kayrak dokulu antrasit yüzey, karşılama duvarını mimari odağa çevirir.',
                'body' => 'Resepsiyon arkası feature wall, sıcak ışık ve doğal taş karakteriyle lobi ölçeğini toparlar. Slate Antrasit paneller 600×1200 mm ebatta, iç mekân uygulamasında hızlı montaj ve düşük yük ile uygulandı. Dikey derz ritmi, otelin sakin ve koyu malzeme paletiyle uyumlu tutuldu.',
                'feats' => ['Feature wall odak', 'Kayrak doku', 'Akşam aydınlatmasına uygun', 'Hafif panel sistemi'],
                'home_status' => true,
                'order' => 1,
            ],
            [
                'slug' => 'restoran-duvari',
                'title' => 'Restoran duvarı',
                'type' => 'restoran',
                'place' => 'indoor',
                'city' => 'ankara',
                'city_label' => 'Ankara',
                'product_name' => 'Rammed Earth Antrasit',
                'year' => '2025',
                'area' => '42 m²',
                'main_image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Ankara’da bir restoran salonu, rammed earth dokusuyla akustik ve görsel derinlik kazandı.',
                'body' => 'Yemek alanı boyunca uzanan antrasit yüzey, masaların sıcak ahşabıyla kontrast kurar. Rammed Earth paneller nem ve lekeye karşı dirençli yapısıyla yoğun kullanıma uygundur. Mutfak açıklığına yakın bölümde kolay temizlenen, anti-kir yüzey tercih edildi.',
                'feats' => ['Yoğun kullanıma uygun', 'Anti-kir yüzey', 'Akustik derinlik', 'Hızlı uygulama'],
                'home_status' => true,
                'order' => 2,
            ],
            [
                'slug' => 'konut-accent-wall',
                'title' => 'Konut accent wall',
                'type' => 'konut',
                'place' => 'indoor',
                'city' => 'konya',
                'city_label' => 'Konya',
                'product_name' => 'Coarse Clothh Krem',
                'year' => '2024',
                'area' => '18 m²',
                'main_image' => 'silvastone/assets/hero/coarse-clothh-krem.jpg',
                'gallery' => [
                    'silvastone/assets/hero/coarse-clothh-krem.jpg',
                    'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Konya’da bir konut oturma odasında kumaş dokulu krem panel, yumuşak ve doğal bir accent wall oluşturur.',
                'body' => 'Televizyon nişi yerine seçilen dokulu yüzey, odayı boğmadan karakter katar. Coarse Clothh Krem, gün ışığında sıcak; akşam LED şeritte ise yumuşak bir rölyef verir. İnce panel yapısı mevcut duvarı kalınlaştırmadan uygulandı.',
                'feats' => ['Kumaş doku', 'Sıcak krem ton', 'İnce kesit', 'Konut ölçeğine uygun'],
                'home_status' => true,
                'order' => 3,
            ],
            [
                'slug' => 'ofis-odak',
                'title' => 'Ofis odak yüzeyi',
                'type' => 'ofis',
                'place' => 'indoor',
                'city' => 'bursa',
                'city_label' => 'Bursa',
                'product_name' => 'Sea Beyaz',
                'year' => '2025',
                'area' => '64 m²',
                'main_image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Bursa’da bir ofis toplantı katında açık tonlu taş paneli, marka duvarını sakin tutar.',
                'body' => 'Sea Beyaz yüzey, cam bölmeler ve açık tavanla birlikte çalışır. Toplantı odasının arka duvarında logo ve projeksiyon için düzgün bir zemin; koridor sürekliliğinde ise aynı doku devam eder. Hafif paneller kat teslim programına uyacak hızda monte edildi.',
                'feats' => ['Açık ton', 'Ofis akustik duvarı', 'Hızlı teslim', 'Marka duvarı'],
                'home_status' => true,
                'order' => 4,
            ],
            [
                'slug' => 'villa-cephe',
                'title' => 'Villa cephesi',
                'type' => 'cephe',
                'place' => 'outdoor',
                'city' => 'antalya',
                'city_label' => 'Antalya',
                'product_name' => 'Tetris Antrasit Desing',
                'year' => '2025',
                'area' => '220 m²',
                'main_image' => 'silvastone/assets/hero/tetris-antrasit.jpg',
                'gallery' => [
                    'silvastone/assets/hero/tetris-antrasit.jpg',
                    'https://images.unsplash.com/photo-1600585154340-0efd65870007?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Antalya’da bir villa bahçe duvarı, gece aydınlatmasında derin antrasit blok dokusuyla mimari gölge üretir.',
                'body' => 'Tetris Antrasit Desing paneller dış mekânda, duvar lambaları ve merdiven LED’leriyle birlikte kurgulandı. Dış cepheye uygun incelik ve su direnci, Akdeniz ikliminde uzun ömür için seçildi. Blok ritmi, bahçe peyzajındaki koyu taş zeminle aynı paleti paylaşır.',
                'feats' => ['Dış cephe', 'Gece aydınlatması', 'Su dayanımı', 'Blok doku'],
                'home_status' => true,
                'order' => 5,
            ],
            [
                'slug' => 'salon-tv-duvari',
                'title' => 'Salon TV duvarı',
                'type' => 'konut',
                'place' => 'indoor',
                'city' => 'istanbul',
                'city_label' => 'İstanbul',
                'product_name' => 'Slate Antrasit',
                'year' => '2025',
                'area' => '24 m²',
                'main_image' => 'silvastone/assets/hero/slate-antrasit.jpg',
                'gallery' => [
                    'silvastone/assets/hero/slate-antrasit.jpg',
                    'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'İstanbul’da bir salon feature wall, TV ünitesini kayrak dokulu antrasit yüzeyle çerçeveler.',
                'body' => 'Asma tavan ışığı ve yan LED şerit, slate dokunun rölyefini öne çıkarır. Panel inceliği, gizli kablo geçişine ve soundbar nişine yer bırakır. İç mekân uygulaması, mevcut alçıpan üzerine yapıştırma sistemiyle tamamlandı.',
                'feats' => ['TV duvarı', 'Gizli kablo', 'LED uyumu', 'Kayrak doku'],
                'home_status' => true,
                'order' => 6,
            ],
            [
                'slug' => 'otel-spa',
                'title' => 'Spa ıslak hacim',
                'type' => 'otel',
                'place' => 'indoor',
                'city' => 'antalya',
                'city_label' => 'Antalya',
                'product_name' => 'Sea Antrasit',
                'year' => '2024',
                'area' => '38 m²',
                'main_image' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600334129128-685c5582fd35?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Antalya otel spa’sında ıslak hacim duvarları, nem kontrolü ve koyu taş karakteriyle çözüldü.',
                'body' => 'Sea Antrasit, nemli ortam ve temizlik rejimine uygun su geçirmez yüzey sunar. Soyunma ve dinlenme koridorunda aynı doku devam ederek spa deneyimini bütünler. Antibakteriyel yüzey, otel operasyonunun hijyen standardına uyar.',
                'feats' => ['Islak hacim', 'Su geçirmez', 'Anti-bakteriyel', 'Nem kontrolü'],
                'home_status' => false,
                'order' => 7,
            ],
            [
                'slug' => 'bahce-duvari',
                'title' => 'Bahçe duvarı',
                'type' => 'konut',
                'place' => 'outdoor',
                'city' => 'tekirdag',
                'city_label' => 'Tekirdağ',
                'product_name' => 'Tetris Krem Desing',
                'year' => '2025',
                'area' => '54 m²',
                'main_image' => 'https://images.unsplash.com/photo-1600585154340-0efd65870007?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1600585154340-0efd65870007?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600047509807-ba8b95e8e6c8?auto=format&fit=crop&w=1400&q=85',
                    'silvastone/assets/hero/tetris-antrasit.jpg',
                ],
                'lead' => 'Tekirdağ’da bir konut bahçesinde krem tetris bloklar, sınır duvarını peyzajın parçası yapar.',
                'body' => 'Dış mekân uygulamasında Tetris Krem Desing, bitki dokusu ve açık taş zeminle uyumlu tutuldu. Güneş ve yağmura karşı dirençli yüzey, bahçe duvarının uzun ömürlü olmasını sağlar. Blok deseni, mesafeden bakıldığında mimari bir doku okutur.',
                'feats' => ['Bahçe duvarı', 'Dış mekân', 'Krem blok doku', 'UV dayanımı'],
                'home_status' => false,
                'order' => 8,
            ],
            [
                'slug' => 'showroom-yuzey',
                'title' => 'Showroom duvarı',
                'type' => 'ofis',
                'place' => 'indoor',
                'city' => 'konya',
                'city_label' => 'Konya',
                'product_name' => 'Mosaic Beyaz',
                'year' => '2025',
                'area' => '48 m²',
                'main_image' => 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Konya Acarkon Store’da mosaic beyaz yüzey, ürünün kendisini sergileyen bir duvar haline gelir.',
                'body' => 'Showroom sergi duvarı hem numune hem mekân kimliği olarak çalışır. Mosaic Beyaz, vitrin ışığında dokuyu okutur; ziyaretçi paneli yakından ve uzaktan deneyimler. Aynı yüzey, danışma arkasında da tekrarlanır.',
                'feats' => ['Showroom sergi', 'Mosaic doku', 'Vitrin ışığı', 'Marka yüzeyi'],
                'home_status' => false,
                'order' => 9,
            ],
            [
                'slug' => 'kafe-teras',
                'title' => 'Kafe teras duvarı',
                'type' => 'restoran',
                'place' => 'outdoor',
                'city' => 'izmir',
                'city_label' => 'İzmir',
                'product_name' => 'Felleving Water Antrasit',
                'year' => '2024',
                'area' => '31 m²',
                'main_image' => 'https://images.unsplash.com/photo-1559339352-11d035aa6de1?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1559339352-11d035aa6de1?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1400&q=85',
                    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'İzmir’de bir kafe teras duvarı, dış mekân oturma alanına antrasit su dokulu yüzey kazandırır.',
                'body' => 'Felleving Water Antrasit, açık terasın rüzgâr ve nemine uygun seçildi. Dikey ritim, saksı ve metal korkulukla birlikte sakin bir arka plan üretir. Akşam saatlerinde duvar yıkama ışığı dokuyu güçlendirir.',
                'feats' => ['Açık teras', 'Dış mekân', 'Su dokusu', 'Yıkama ışık'],
                'home_status' => false,
                'order' => 10,
            ],
            [
                'slug' => 'otel-cephe',
                'title' => 'Otel dış cephe',
                'type' => 'cephe',
                'place' => 'outdoor',
                'city' => 'mardin',
                'city_label' => 'Mardin',
                'product_name' => 'Tetris Antrasit Desing',
                'year' => '2025',
                'area' => '310 m²',
                'main_image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
                    'silvastone/assets/hero/tetris-antrasit.jpg',
                    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=70',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Mardin’de bir otel cephesi, tetris blok ritmiyle kente yeni bir taş okuması ekler.',
                'body' => 'Dış cephe panelleri, güneş ve toza karşı dayanıklı antrasit yüzeyle uygulandı. Giriş saçağı ve üst kat ritmi aynı dokuyu paylaşır. Hafif sistem, mevcut strüktüre ek yük bindirmeden büyük alan kaplamayı mümkün kıldı.',
                'feats' => ['Büyük cephe', 'Dış iklim', 'Hafif sistem', 'Blok ritmi'],
                'home_status' => false,
                'order' => 11,
            ],
            [
                'slug' => 'residans-salon',
                'title' => 'Rezidans salonu',
                'type' => 'konut',
                'place' => 'indoor',
                'city' => 'ankara',
                'city_label' => 'Ankara',
                'product_name' => 'Banana Leaf Pattern Krem',
                'year' => '2024',
                'area' => '22 m²',
                'main_image' => 'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1400&q=85',
                'gallery' => [
                    'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1400&q=85',
                    'silvastone/assets/hero/coarse-clothh-krem.jpg',
                    'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85',
                ],
                'lead' => 'Ankara’da bir rezidans salonunda yaprak desenli krem panel, doğal ve yumuşak bir iç mekân karakteri kurar.',
                'body' => 'Banana Leaf Pattern Krem, oturma grubunun arkasında tek bir duvar olarak kullanıldı. Desen ölçeği salona göre seçildi; fazla tekrar etmeden doğal bir ritim verir. İç mekân, gün ışığı ve abajur ışığında iki farklı okuma sunar.',
                'feats' => ['Desenli yüzey', 'Konut salonu', 'Krem palet', 'Tek duvar odak'],
                'home_status' => false,
                'order' => 12,
            ],
        ];
    }
}
